<?php

return [
    'roles' => [
        'admin' => [
            'label' => 'Admin',
            'features' => [
                'Kelola user staff (admin, cashier, casier, courier, manager)',
                'Kelola cabang, tarif, kendaraan, dan konfigurasi sistem',
                'Akses penuh data shipment, payment, dan laporan',
                'Monitoring task courier, verifikasi pembayaran, dan laporan manager lintas cabang',
                'Melihat audit log dan monitoring status sistem',
            ],
            'tables' => [
                'users' => ['create', 'read', 'update', 'delete'],
                'branches' => ['create', 'read', 'update', 'delete'],
                'rates' => ['create', 'read', 'update', 'delete'],
                'vehicles' => ['create', 'read', 'update', 'delete'],
                'customers' => ['read', 'update'],
                'shipments' => ['create', 'read', 'update', 'delete'],
                'shipment_items' => ['create', 'read', 'update', 'delete'],
                'shipment_trackings' => [],
                'payments' => ['create', 'read', 'update', 'delete'],
            ],
        ],
        'manager' => [
            'label' => 'Manager',
            'features' => [
                'Melihat dashboard KPI operasional dan keuangan',
                'Approval perubahan tarif khusus dan eskalasi operasional',
                'Monitoring performa cabang/kurir',
                'Export laporan performa dan transaksi',
                'Akses dashboard laporan KPI multi-cabang',
            ],
            'tables' => [
                'users' => ['read'],
                'branches' => ['read'],
                'rates' => ['read'],
                'vehicles' => ['read'],
                'customers' => ['read'],
                'shipments' => ['read', 'update'],
                'shipment_items' => ['read'],
                'shipment_trackings' => [],
                'payments' => ['read'],
            ],
        ],
        'cashier' => [
            'label' => 'Cashier',
            'features' => [
                'Monitoring transaksi Midtrans yang masih pending atau gagal',
                'Audit invoice, nominal, dan status sinkronisasi pembayaran',
                'Cetak invoice dan bukti transaksi customer',
                'Rekonsiliasi transaksi harian berbasis status gateway',
            ],
            'tables' => [
                'users' => ['read'],
                'branches' => ['read'],
                'rates' => ['read'],
                'vehicles' => ['read'],
                'customers' => ['read'],
                'shipments' => ['read', 'update'],
                'shipment_items' => ['read'],
                'shipment_trackings' => ['read'],
                'payments' => ['create', 'read', 'update'],
            ],
        ],
        'casier' => [
            'label' => 'Casier',
            'features' => [
                'Monitoring transaksi Midtrans yang masih pending atau gagal',
                'Audit invoice, nominal, dan status sinkronisasi pembayaran',
                'Cetak invoice dan bukti transaksi customer',
                'Rekonsiliasi transaksi harian berbasis status gateway',
            ],
            'tables' => [
                'users' => ['read'],
                'branches' => ['read'],
                'rates' => ['read'],
                'vehicles' => ['read'],
                'customers' => ['read'],
                'shipments' => ['read', 'update'],
                'shipment_items' => ['read'],
                'shipment_trackings' => ['read'],
                'payments' => ['create', 'read', 'update'],
            ],
        ],
        'courier' => [
            'label' => 'Courier',
            'features' => [
                'Melihat shipment yang di-assign ke dirinya',
                'Update progress pickup, transit, sampai delivered',
                'Input bukti pengiriman (foto/lokasi/deskripsi)',
                'Melihat riwayat tugas pribadi',
                'Akses halaman task courier untuk update status cepat',
            ],
            'tables' => [
                'users' => ['read'],
                'branches' => ['read'],
                'rates' => [],
                'vehicles' => ['read', 'update'],
                'customers' => ['read'],
                'shipments' => ['read', 'update'],
                'shipment_items' => ['read'],
                'shipment_trackings' => ['create', 'read', 'update'],
                'payments' => ['read'],
            ],
        ],
        'customer' => [
            'label' => 'Customer',
            'features' => [
                'Registrasi dan login customer',
                'Membuat order pengiriman dan memilih penerima',
                'Melihat tracking real-time berdasarkan nomor resi',
                'Membayar kiriman dan melihat riwayat transaksi pribadi',
            ],
            'tables' => [
                'users' => [],
                'branches' => ['read'],
                'rates' => ['read'],
                'vehicles' => [],
                'customers' => ['read', 'update'],
                'shipments' => ['create', 'read'],
                'shipment_items' => ['create', 'read'],
                'shipment_trackings' => ['read'],
                'payments' => ['create', 'read'],
            ],
        ],
    ],
];
